services:

  rocksdb:
    image: ubuntu
    container_name: rocksdb
    command: tail -f /dev/null
    volumes:
      - ./rocksdb-data:/var/lib/rocksdb

  kafka:
    build:
      context: .
      dockerfile: dockerfile.kafka  # Custom Dockerfile to install Kafka & Kafka Streams app
    container_name: kafka
    ports:
      - "9092:9092"
      - "8080:8080"  # Expose Kafka Streams app API
    env_file:
      - kafka.env
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    restart: unless-stopped
