# Use Confluent Kafka base image
FROM confluentinc/cp-kafka:7.9.0

# Set working directory
WORKDIR /etc/kafka

# Ensure Kafka uses the custom server.properties
# COPY kafka-config/server.properties /etc/kafka/server.properties

# Set up the entrypoint to run Kafka
CMD ["/etc/confluent/docker/run"]
